// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package token is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	TokenMapping
*/
package token

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TokenMapping struct {
	// ID is the storage path identifier of the token
	ID string `sentinel:"" protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Accessor is the secondary identifier of the token
	Accessor string `sentinel:"" protobuf:"bytes,2,opt,name=accessor" json:"accessor,omitempty"`
	// TokenID is the identifier of the token
	TokenID string `sentinel:"" protobuf:"bytes,3,opt,name=token_id,json=tokenId" json:"token_id,omitempty"`
	// ParentID is the identifier of the token's parent token
	ParentID string `sentinel:"" protobuf:"bytes,4,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
}

func (m *TokenMapping) Reset()                    { *m = TokenMapping{} }
func (m *TokenMapping) String() string            { return proto.CompactTextString(m) }
func (*TokenMapping) ProtoMessage()               {}
func (*TokenMapping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TokenMapping) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *TokenMapping) GetAccessor() string {
	if m != nil {
		return m.Accessor
	}
	return ""
}

func (m *TokenMapping) GetTokenID() string {
	if m != nil {
		return m.TokenID
	}
	return ""
}

func (m *TokenMapping) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func init() {
	proto.RegisterType((*TokenMapping)(nil), "token.TokenMapping")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xc9, 0xcf, 0x4e, 0xcd, 0x53, 0x2a,
	0xe2, 0xe2, 0x09, 0x01, 0x31, 0x7c, 0x13, 0x0b, 0x0a, 0x32, 0xf3, 0xd2, 0x85, 0xf8, 0xb8, 0x98,
	0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0xa4, 0xb8, 0x38,
	0x12, 0x93, 0x93, 0x53, 0x8b, 0x8b, 0xf3, 0x8b, 0x24, 0x98, 0xc0, 0xa2, 0x70, 0xbe, 0x90, 0x24,
	0x17, 0x07, 0xd8, 0x90, 0xf8, 0xcc, 0x14, 0x09, 0x66, 0xb0, 0x1c, 0x3b, 0x98, 0xef, 0x99, 0x22,
	0x24, 0xcd, 0xc5, 0x59, 0x90, 0x58, 0x94, 0x9a, 0x57, 0x02, 0x92, 0x63, 0x81, 0xe8, 0x83, 0x08,
	0x78, 0xa6, 0x24, 0xb1, 0x81, 0x5d, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xc7, 0x69,
	0x3c, 0x90, 0x00, 0x00, 0x00,
}
